// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDorm.Data;

#nullable disable

namespace SmartDorm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127085047_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SmartDorm.Models.Dormitory", b =>
                {
                    b.Property<int>("DormitoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CampusLocation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("DormitoryId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Dormitories");

                    b.HasData(
                        new
                        {
                            DormitoryId = 1,
                            Address = "Campus North Zone",
                            CampusLocation = "North",
                            GenderType = 0,
                            ManagerId = 1,
                            Name = "Sadra",
                            TotalCapacity = 300
                        },
                        new
                        {
                            DormitoryId = 2,
                            Address = "Campus West Zone",
                            CampusLocation = "West",
                            GenderType = 1,
                            ManagerId = 1,
                            Name = "Sadaf",
                            TotalCapacity = 250
                        });
                });

            modelBuilder.Entity("SmartDorm.Models.DormitoryManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DormitoryManagers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "mosayebi",
                            PhoneNumber = "555-1234",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartDorm.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenderType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPrivateBathroom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WingOrBlock")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.HasIndex("DormitoryId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Capacity = 2,
                            DormitoryId = 1,
                            Floor = 1,
                            GenderType = 0,
                            HasPrivateBathroom = false,
                            IsActive = true,
                            RoomNumber = 336,
                            WingOrBlock = 3
                        },
                        new
                        {
                            RoomId = 2,
                            Capacity = 3,
                            DormitoryId = 1,
                            Floor = 1,
                            GenderType = 0,
                            HasPrivateBathroom = true,
                            IsActive = true,
                            RoomNumber = 212,
                            WingOrBlock = 1
                        },
                        new
                        {
                            RoomId = 3,
                            Capacity = 2,
                            DormitoryId = 2,
                            Floor = 2,
                            GenderType = 1,
                            HasPrivateBathroom = true,
                            IsActive = true,
                            RoomNumber = 5,
                            WingOrBlock = 3
                        });
                });

            modelBuilder.Entity("SmartDorm.Models.SpecialCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConditionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Needs")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("SpecialConditions");
                });

            modelBuilder.Entity("SmartDorm.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthdayYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOfStudy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SmartDorm.Models.StudentPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoiseToleranceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomAtmosphere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SleepHabit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyStyle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentPreferences");
                });

            modelBuilder.Entity("SmartDorm.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Role = 1,
                            Username = "dormmanager"
                        });
                });

            modelBuilder.Entity("SmartDorm.Models.Dormitory", b =>
                {
                    b.HasOne("SmartDorm.Models.DormitoryManager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SmartDorm.Models.DormitoryManager", b =>
                {
                    b.HasOne("SmartDorm.Models.UserAccount", "UserAccount")
                        .WithOne("DormitoryManager")
                        .HasForeignKey("SmartDorm.Models.DormitoryManager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SmartDorm.Models.Room", b =>
                {
                    b.HasOne("SmartDorm.Models.Dormitory", "Dormitory")
                        .WithMany("Rooms")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("SmartDorm.Models.SpecialCondition", b =>
                {
                    b.HasOne("SmartDorm.Models.Student", "Student")
                        .WithMany("SpecialConditions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartDorm.Models.Student", b =>
                {
                    b.HasOne("SmartDorm.Models.UserAccount", "UserAccount")
                        .WithOne("Student")
                        .HasForeignKey("SmartDorm.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SmartDorm.Models.StudentPreference", b =>
                {
                    b.HasOne("SmartDorm.Models.Student", "Student")
                        .WithOne("Preference")
                        .HasForeignKey("SmartDorm.Models.StudentPreference", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartDorm.Models.Dormitory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartDorm.Models.Student", b =>
                {
                    b.Navigation("Preference");

                    b.Navigation("SpecialConditions");
                });

            modelBuilder.Entity("SmartDorm.Models.UserAccount", b =>
                {
                    b.Navigation("DormitoryManager");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
